# backend
backend = "glx"
vsync = true #false
fading = true
# round corners
corner-radius = 8

# fade (legacy, harmless to keep)
fade-delta = 8

# exclude stuff
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
];

#################################
#        ANIMATIONS (v12+)      #
#################################

animations = (

#################################
# Geometry change (keep yours)
#################################
    {
    triggers = [ "geometry" ];
    duration = "0.15";
    preset = "geometry-change";
    scale = "1.0";
    offset-y = {
    curve    = "cubic-bezier(0, 0, 0.58, 1)";   # ease-out
    duration = 0.15;
    start    = "window-height";
    end      = 0;
    };
    offset-x = "offset-y";
    shadow-offset-y = "offset-y";
    shadow-offset-x = "offset-x";
    },

#################################
# OPEN → slide up + fade + slight zoom
#################################
{
  triggers = ["open" ];
  opacity = {
    duration = 0.15;
    curve = "cubic-bezier(0, 0, 0.58, 1)";
    start = 0;
    end = "window-raw-opacity";
  };
  offset-y = {
    curve    = "cubic-bezier(0, 0, 0.58, 1)";   # ease-out
      duration = 0.15;
    start    = "window-height";
    end      = 0;
  };
  shadow-offset-y = "offset-y";
},


{
  triggers = ["show"];
  opacity = {
    duration = 0.25;
    curve = "cubic-bezier(0.42, 0, 1, 1)";
    start = 0;
    end = "window-raw-opacity";
  };

  #offset-x = {
    #curve    = "cubic-bezier(0, 0, 0.58, 1)";   # ease-out
      #duration = 0.15;
    #start    = "window-width";
    #end      = "windowoffset-x";
  #};
  #shadow-offset-x = "offset-x";
  preset="appear";
  scale="0.75";
  duration="0.15";
},
#################################
# CLOSE → slide down + fade
#################################
{
  triggers = ["close"];

  opacity = {
    duration = 0.15;
    curve    = "cubic-bezier(0, 0, 0.58, 1)";   # ease-out
      start    = "window-raw-opacity-before";
    end      = 0;
  };
  offset-y = {
    curve    = "cubic-bezier(0, 0, 0.58, 1)";   # ease-out
      duration = 0.5;
    end      = "window-height";
    start    = 0;
  };
  shadow-offset-y = "offset-y";
},

{
  triggers = ["hide"];
  opacity = {
    curve = "cubic-bezier(0, 0, 0.58, 1)";
    start = "window-raw-opacity-before";
    end = 0;
  };
  #offset-x = {
    #curve    = "cubic-bezier(0, 0, 0.58, 1)";   # ease-out
      #duration = 0.15;
    #start    = "window-width";
    #end      = "windowoffset-x";
  #};
  #shadow-offset-x = "offset-x";
  preset="disappear";
  scale="0.75";
  duration="0.15";
}
);

#################################
#            RULES              #
#################################

opacity-rule = [
  "80:class_g = 'Sakura'"
];

#opacity-rule = [
#  "80:class_g = 'firefox'"
#];

blur:
{
  #method = "gaussian";
  size = 6;
  deviation = 6.0;
  method = "dual_kawase";
  strength = 6;
};
