-- Generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#101418",
	base01 = "#0b0e13",
	base02 = "#191c20",
	base03 = "#42474e",
	base04 = "#c2c7cf",
	base05 = "#e1e2e8",
	base06 = "#2d3135",
	base07 = "#36393e",

	base08 = "#cbacde",
	base09 = "#d6bee5",
	base0A = "#bac8db",
	base0B = "#9fcafc",
	base0C = "#524060",
	base0D = "#174974",
	base0E = "#3b4857",
	base0F = "#98adca",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#174974",
	fg = "#d0e4ff", -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ "String", "TSString" }, {
	fg = "#b487cf",
})

-- Grey out comments
set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#8c9199",
	italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#d6bee5",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#bac8db",
})

set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "#34618e",
})
